name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      env:
        PIPEDRIVE_API_KEY: ${{ secrets.PIPEDRIVE_API_KEY }}
        PIPEDRIVE_SUBDOMAIN: ${{ secrets.PIPEDRIVE_SUBDOMAIN }}
      run: bundle exec rake
